Lucascserrate/cava_verdot

server/src/routes/controllers/products.js
server/src/routes/products.routes.js

permite ingresar un nuevo producto con el siguiente modelo:
{
"id": 1,
"name": "La Montesa 2018",
"description": "Lorem... y mas texto",
"stock": 52,
"price": 14.65,
"image": ["https://media.drinksandco.com/wines/la-montesa-1750981_e.jpg"](https://media.drinksandco.com/wines/la-montesa-1750981_e.jpg),
"origen": "Spain",
"category": "Wine",
"sub_category": "Red Wine"
}

Rene - ruta y controlador postProduct

---

server/src/routes/controllers/categories.js

permite cargar las categorías a la base de datos local, a partir de la información que se encuentra en el archivo api.js

cargando categorías a la BD 05/01

---

server/index.js
server/src/routes/index.js

rutas 
1° /categories
2° /countries
3°/drinks

reparando bugs 06/01/ 9:59

---

server/src/routes/controllers/drinksDB.js
server/src/routes/controllers/getProducts.js
server/src/routes/controllers/postProducts.js
server/src/routes/products.routes.js

Se separo el controlador postProducts a un nuevo archivo

cambios postProducts (modularización) 06/01 11:33

---

server/src/routes/controllers/getProducts.js
server/src/routes/products.routes.js

se puede solicitar una búsqueda por categoría sin preocuparse por la las mayusculas o minuscuyas

filtro por categoría insensitive case 06/01

---

server/src/routes/controllers/getProducts.js

en la ruta .../productos/:id  se solicita una bebida en específico

getProducts por ID funcionando 06/01 19:45 arg

---

client/src/components/Searchbar/Searchbar.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

con esto ya deberia estar funcionar la busqueda

action y reducer para searchbar v2, 08/01

---

client/src/components/Navbar/Navbar.jsx
client/src/components/Searchbar/Searchbar.jsx
client/src/components/Store/Store.jsx
client/src/redux/actions.js
client/src/redux/reducer.js

ya esta, esta andando (funciona)

componente searchbar funcionando v2 08/01

---

client/src/components/Carousel/Carousel.jsx
client/src/components/Details/Details.jsx
client/src/components/Home/Home.jsx
client/src/components/Navbar/Navbar.jsx

agregue varios elementos a cosas como los detalles, descripción , etc

detalles extra generales para la presentacion 09/01

---

server/api.js
server/index.js
server/src/db.js
server/src/models/User.js
server/src/routes/controllers/postUser.js
server/src/routes/index.js
server/src/routes/users.routes.js

se ha realizado algunas mejoras en la validación del modelo User: permite aceptar tildes y dieresis
en controlador de postUser se realiza validaciones de:
-name: obligatorio, permite letras tildes y dieresis en vocales 
-surname: opcional, permite letras tildes y dieresis en vocales
-age: obligatorio, debe ser mayor que 18
-email: obligatorio, debe tener el formato correcto
-password: obligatorio
-image: opcional, si se agrega debe tener el formato URL
en caso de errores se devuelve un objeto con todos los errores

post user 10/01 08:38

---

client/src/components/AsideFilters/AsideFilters.jsx
client/src/components/Details/Details.jsx
client/src/components/Searchbar/Searchbar.jsx
client/src/redux/actions.js

En el back antes recibiamos por ID un objeto, luego del ultimo PR nos traia un array con un objeto

resolviendo que en el detalle no traia los datos

---

server/api.js
server/src/db.js
server/src/models/Role.js
server/src/models/ShopingCart.js
server/src/routes/controllers/getShopingCart.js
server/src/routes/controllers/postAddToShopingCart.js
server/src/routes/index.js
server/src/routes/shopingCart.routes.js
server/src/routes/users.routes.js

@Lucascserrate 
ruta pos:    .../shopingCart    (también permite actualizar)
json que se solicita: 
userId: opcional
drinkId: oligatorio
amount: entre 0 y stock maximo de bebida
responde con:
userId: para siguientes solicitudes
mensaje: de confirmacion
ruta get :    .../shopingCart?userId

modelo shopingCart, ruta posPut get 11/01 22:51

---

server/src/routes/controllers/deleteItemShopingCart.js
server/src/routes/controllers/getShopingCart.js
server/src/routes/controllers/postAddToShopingCart.js
server/src/routes/shopingCart.routes.js

actualización de ruta get, post y put del carrito
implementacion de ruta delete del carrito

get post put and delete de shopingCart 13/01 02:57

---

client/src/components/FormularioPostProduct/PostProductForm.jsx

Paises agregados al form, solucionados los errores

errores solucionados postProducts

---

server/src/models/User.js
server/src/routes/controllers/getUserById.js
server/src/routes/controllers/mailer.js
server/src/routes/controllers/postUser.js
server/src/routes/controllers/putUser.js
server/src/routes/users.routes.js

ruta getUserById ... /users/:userId
ruta putUser        ... /users/:userId
parche en modelo User no es obligatorio el campo address
parche en la ruta postUser no es obligatorio el campo address

rutas get user put user parche modelo user

---

server/src/routes/controllers/deleteUser.js
server/src/routes/users.routes.js

pasar por params userId y por body status(ya sea true o false)

Ruta delete user con borrado logico

---

server/src/routes/controllers/mailer.js
server/src/routes/controllers/postUser.js

el usuario no perderá información en el momento de registrarse

parche post product userId

---

server/src/routes/controllers/getUserById.js

si el usuario ya cuenta con address registrado lo trae en caso contrario traera un null

getUserById tambien trae address

---

server/src/routes/controllers/getAllCountries.js
server/src/routes/controllers/getAllStatesByCountry.js
server/src/routes/controllers/getCitiesByState.js
server/src/routes/controllers/mailer.js
server/src/routes/users.routes.js

get .../users/address/allCountries
get .../users/address/allStates/:countryId
si se manda null se respondera un array con un objeto que indicará lo errores el error name indica seleccionar pais
get .../users/address/allCities/:stateId
si se manda null se respondera un array con un objeto que indicará lo errores el error name indica seleccionar estado

rutas para traer pais estado y ciudad

---

server/src/db.js

por algun motivo tenia una base de datos que no funciona

Arreglo de la base de datos
